### ISSUE TITLE
Add branch 1.0.1 for Keys

### ISSUE THREAD

**Issue by nanoxd** [ashfurrow/empty-podspec#2]
When running pod install with cocoapod-keys enabled, I receive an error during install. 

```
git clone https://github.com/ashfurrow/empty-podspec.git ~/dir/App/Pods/Keys --single-branch --depth 1 --branch 1.0.1

Cloning into ~/dir/App/Pods/Keys...

warning: Could not find remote branch 1.0.1 to clone
```

Adding the branch should eliminate the issue. :bow: Thanks for the hard work!

**Comment by ashfurrow** [comment]
What I've done is created a tag called `1.0.1` that should do it – can you try again and let me know?

**Comment by nanoxd** [comment]
It works now! Thanks!

**Comment by ashfurrow** [comment]
Super! :smile_cat:
